/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca.biblioteca2;


import biblioteca.biblioteca2.views.Devoluciones;
import biblioteca.biblioteca2.views.Libro;
import biblioteca.biblioteca2.views.Prestamos;
import biblioteca.biblioteca2.views.Principal;
import biblioteca.biblioteca2.views.Reporte;
import biblioteca.biblioteca2.views.SubirUsuarios;
import biblioteca.biblioteca2.views.Usuario;
import biblioteca.biblioteca2.views.subirLibro;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author USUARIO
 */
public class biblioteca extends javax.swing.JFrame {

    /**
     * Creates new form biblioteca
     */
    public biblioteca() {
        initComponents();
        InitStyles();
        setDate();
        InitContent();
    }
    
    private  void InitContent() {
        ShowJPanel(new Principal());
    }
    
    public  static void ShowJPanel(JPanel p) {
        p.setSize(1000, 1000);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    
    
    private void setDate(){
        
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        Fecha.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
    
    }
    
    private void InitStyles(){
        mensaje.putClientProperty( "FlatLaf.style", "font: 14 $light.font" );
        mensaje.setForeground(Color.black);
        jLabel1.putClientProperty( "FlatLaf.style", "font: bold $h3.regular.font" );
        jLabel1.setForeground(Color.white);
        Fecha.putClientProperty( "FlatLaf.style", "font:24 $light.font" );
        Fecha.setForeground(Color.white);
        title.putClientProperty( "FlatLaf.style", "font:24 $light.font" );
        title.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fondo = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        devoluciones = new javax.swing.JButton();
        principal = new javax.swing.JButton();
        prestamos1 = new javax.swing.JButton();
        usuarios = new javax.swing.JButton();
        libros = new javax.swing.JButton();
        reportes = new javax.swing.JButton();
        cabeza = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1050, 660));
        setPreferredSize(new java.awt.Dimension(1235, 700));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setMinimumSize(new java.awt.Dimension(1223, 1020));

        menu.setBackground(new java.awt.Color(13, 171, 161));
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu.setPreferredSize(new java.awt.Dimension(270, 431));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Libreria");
        menu.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 270, 37));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        menu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 91, -1, -1));

        devoluciones.setBackground(new java.awt.Color(21, 101, 192));
        devoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar-multiple-check.png"))); // NOI18N
        devoluciones.setText("Devoluciones");
        devoluciones.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        devoluciones.setBorderPainted(false);
        devoluciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        devoluciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        devoluciones.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        devoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolucionesActionPerformed(evt);
            }
        });
        menu.add(devoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 270, 50));
        devoluciones.getAccessibleContext().setAccessibleName("Principal");

        principal.setBackground(new java.awt.Color(21, 101, 192));
        principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-outline.png"))); // NOI18N
        principal.setText("Principal");
        principal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        principal.setBorderPainted(false);
        principal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        principal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        principal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalActionPerformed(evt);
            }
        });
        menu.add(principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 170, 270, 50));

        prestamos1.setBackground(new java.awt.Color(21, 101, 192));
        prestamos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar-plus.png"))); // NOI18N
        prestamos1.setText("Prestamo");
        prestamos1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        prestamos1.setBorderPainted(false);
        prestamos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prestamos1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        prestamos1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        prestamos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamos1ActionPerformed(evt);
            }
        });
        menu.add(prestamos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 270, 50));

        usuarios.setBackground(new java.awt.Color(21, 101, 192));
        usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/account-multiple.png"))); // NOI18N
        usuarios.setText("Usuarios");
        usuarios.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        usuarios.setBorderPainted(false);
        usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usuarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosActionPerformed(evt);
            }
        });
        menu.add(usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 270, 50));

        libros.setBackground(new java.awt.Color(21, 101, 192));
        libros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book-open-page-variant.png"))); // NOI18N
        libros.setText("Libros");
        libros.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        libros.setBorderPainted(false);
        libros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        libros.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosActionPerformed(evt);
            }
        });
        menu.add(libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 270, 50));

        reportes.setBackground(new java.awt.Color(21, 101, 192));
        reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file-chart.png"))); // NOI18N
        reportes.setText("Reportes");
        reportes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        reportes.setBorderPainted(false);
        reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reportes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });
        menu.add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 270, 50));

        cabeza.setBackground(new java.awt.Color(25, 118, 210));
        cabeza.setPreferredSize(new java.awt.Dimension(872, 150));
        cabeza.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Administración / Control / Biblioteca");
        cabeza.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 37, 423, 38));

        Fecha.setText("Hoy es {dayname} {day} de {month} del {year}");
        cabeza.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 81, 490, 45));

        mensaje.setText("Biblioteca FEMPA");

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(761, 200));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cabeza, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE))
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(mensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cabeza, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void devolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolucionesActionPerformed
       ShowJPanel(new Devoluciones());
    }//GEN-LAST:event_devolucionesActionPerformed

    private void principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalActionPerformed
        ShowJPanel(new Principal());
    }//GEN-LAST:event_principalActionPerformed

    private void prestamos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamos1ActionPerformed
        ShowJPanel(new Prestamos());
    }//GEN-LAST:event_prestamos1ActionPerformed

    private void usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosActionPerformed
        ShowJPanel(new Usuario());
    }//GEN-LAST:event_usuariosActionPerformed

    private void librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosActionPerformed
        ShowJPanel(new Libro());
    }//GEN-LAST:event_librosActionPerformed

    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
        ShowJPanel(new Reporte());
    }//GEN-LAST:event_reportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatMaterialLighterIJTheme.setup();
        
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha;
    private javax.swing.JPanel cabeza;
    private static javax.swing.JPanel content;
    private javax.swing.JButton devoluciones;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton libros;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPanel menu;
    private javax.swing.JButton prestamos1;
    private javax.swing.JButton principal;
    private javax.swing.JButton reportes;
    private javax.swing.JLabel title;
    private javax.swing.JButton usuarios;
    // End of variables declaration//GEN-END:variables
}
