/* * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package biblioteca.biblioteca2;

import biblioteca.Usuario.Supervisor;
import biblioteca.biblioteca2.login.DAOLoginImpl;
import biblioteca.biblioteca2.viewsSupervisor.Principal;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;

/**
 *
 * @author USUARIO
 */
public class menuSupervisor extends javax.swing.JPanel {
    
    
    private Supervisor s;
    private LocalDateTime fechaEntrada;
    private LocalDateTime fechaSalida;
    /**
     * Creates new form menuSupervisor
     */
    public menuSupervisor(String nombre, String contrasena) throws Exception{
        DAOLoginImpl dao = new DAOLoginImpl();
        s = dao.supervisorIniciado(nombre, contrasena);        
        fechaEntrada = LocalDateTime.now();
        initComponents();        
        setWelcome(s.getNombre(),s.getApellido());
        InitStyles();  
        ShowJPanel(new Principal());
    }
    
    private  void ShowJPanel(JPanel p) {
        p.setSize(1235, 1000);
        p.setLocation(0,0);
        // [1237, 1523]
        principal.removeAll();
        principal.add(p, BorderLayout.CENTER);
        principal.revalidate();
        principal.repaint();
        
    }
    
    private void setWelcome(String nombre, String apellido){
        
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        fecha.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
        intro.setText("Bienvenido " + nombre +" " + apellido+".");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        botonEmpleados = new javax.swing.JButton();
        botonFichadoEmp = new javax.swing.JButton();
        botonProductividad = new javax.swing.JButton();
        botonFichadoSup = new javax.swing.JButton();
        head = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        intro = new javax.swing.JLabel();
        principal = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1235, 1026));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(13, 171, 161));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setText("Supervisor");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 68, 114, 36));

        botonSalir.setBackground(new java.awt.Color(21, 101, 192));
        botonSalir.setText("SALIR");
        botonSalir.setBorder(new javax.swing.border.MatteBorder(null));
        botonSalir.setBorderPainted(false);
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 400, 80));

        botonEmpleados.setBackground(new java.awt.Color(21, 101, 192));
        botonEmpleados.setText("Empleados");
        botonEmpleados.setBorder(new javax.swing.border.MatteBorder(null));
        botonEmpleados.setBorderPainted(false);
        botonEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(botonEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 400, 80));

        botonFichadoEmp.setBackground(new java.awt.Color(21, 101, 192));
        botonFichadoEmp.setText("Fichado Empleados");
        botonFichadoEmp.setBorder(new javax.swing.border.MatteBorder(null));
        botonFichadoEmp.setBorderPainted(false);
        botonFichadoEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonFichadoEmp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonFichadoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFichadoEmpActionPerformed(evt);
            }
        });
        jPanel1.add(botonFichadoEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 400, 80));

        botonProductividad.setBackground(new java.awt.Color(21, 101, 192));
        botonProductividad.setText("Productividad");
        botonProductividad.setBorder(new javax.swing.border.MatteBorder(null));
        botonProductividad.setBorderPainted(false);
        botonProductividad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonProductividad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(botonProductividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 400, 80));

        botonFichadoSup.setBackground(new java.awt.Color(21, 101, 192));
        botonFichadoSup.setText("Fichado Supervisores");
        botonFichadoSup.setBorder(new javax.swing.border.MatteBorder(null));
        botonFichadoSup.setBorderPainted(false);
        botonFichadoSup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonFichadoSup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(botonFichadoSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 400, 80));

        head.setBackground(new java.awt.Color(13, 171, 161));
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fecha.setText("Hoy es {dia}");
        head.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 560, 50));

        intro.setText("Bienvenido {nombre}");
        head.add(intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 540, 40));

        principal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                    .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonFichadoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFichadoEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFichadoEmpActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        super.removeSupervisor();
    }//GEN-LAST:event_botonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEmpleados;
    private javax.swing.JButton botonFichadoEmp;
    private javax.swing.JButton botonFichadoSup;
    private javax.swing.JButton botonProductividad;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel head;
    private javax.swing.JLabel intro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel principal;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    private void InitStyles(){
        titulo.putClientProperty( "FlatLaf.st,"
                + "yle", "font: bold $h3.regular.font" );
        titulo.setForeground(Color.WHITE); 
        fecha.putClientProperty( "FlatLaf.style", "font:24 $light.font" );
        fecha.setForeground(Color.white); 
        intro.putClientProperty( "FlatLaf.style", "font:24 $light.font" );
        intro.setForeground(Color.white); 
    }
}
