/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package biblioteca.biblioteca2.views;

import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class Prestamos extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Prestamos() {
        initComponents();
        InitStyles();
    }
    
    private void InitStyles(){
        titutloFolioUsuario.putClientProperty( "FlatLaf.styleClass", "large" );
        titutloFolioUsuario.setForeground(Color.black);
        folioUsuario.putClientProperty( "FlatLaf.style", "font: bold $h3.regular.font" );
        folioUsuario.setForeground(Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        IDLibro = new javax.swing.JTextField();
        tituloIDLibro = new javax.swing.JLabel();
        titutloFolioUsuario = new javax.swing.JLabel();
        folioUsuario = new javax.swing.JTextField();
        buttonPrestar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 460));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prestamo.gif"))); // NOI18N
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 10, 590, 460));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 10, 340));

        IDLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLibroActionPerformed(evt);
            }
        });
        jPanel1.add(IDLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 320, 40));

        tituloIDLibro.setText("Libro ID");
        jPanel1.add(tituloIDLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        titutloFolioUsuario.setText("Folio Usuario:");
        jPanel1.add(titutloFolioUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        folioUsuario.setText("Ingrese el folio del usuario");
        folioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folioUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(folioUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 320, 40));

        buttonPrestar.setBackground(new java.awt.Color(18, 90, 173));
        buttonPrestar.setText("Prestar");
        buttonPrestar.setBorderPainted(false);
        buttonPrestar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPrestar.setPreferredSize(new java.awt.Dimension(90, 31));
        buttonPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrestarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 320, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IDLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDLibroActionPerformed

    private void folioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folioUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_folioUsuarioActionPerformed

    private void buttonPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrestarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPrestarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDLibro;
    private javax.swing.JButton buttonPrestar;
    private javax.swing.JTextField folioUsuario;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel tituloIDLibro;
    private javax.swing.JLabel titutloFolioUsuario;
    // End of variables declaration//GEN-END:variables
}
