/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package biblioteca.biblioteca2.views;

import biblioteca.biblioteca2.DAOUsuarioImpl;
import biblioteca.interfacez.DAOUser;
import biblioteca.models.UsersDB;
import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class SubirUsuarios extends javax.swing.JPanel {

    boolean isEdition = false;
    UsersDB user;
    public SubirUsuarios() {
        initComponents();       
        InitStyles();
    }
    
    
    public SubirUsuarios(UsersDB user) {        
        initComponents();
        isEdition = true;
        this.user = user;
        InitStyles();
    }
    
    
    
    private void InitStyles(){
        titulo.putClientProperty("FlatLaf.styleClass", "h1");
        titulo.setForeground(Color.black);
        campoNombre.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del usuario");
        campoApellido.putClientProperty("JTextField.placeholderText", "Ingrese el apellido del usuario");
        campoDni.putClientProperty("JTextField.placeholderText", "Ingrese el DNI del usuario");
        campoEdad.putClientProperty("JTextField.placeholderText", "Ingrese el edad del usuario");
        if(isEdition){
            titulo.setText("Editar Usuario");
            jButton1.setText("Guardar");
            
            if(user != null){
                campoNombre.setText(user.getNombre());
                campoApellido.setText(user.getApellido());
                campoDni.setText(user.getDni());
                campoEdad.setText(Integer.toString(user.getEdad()));
            }
        }else{
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bc = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        tituloNombre = new javax.swing.JLabel();
        campoDni = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        tituloNombre1 = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        tituloNombre2 = new javax.swing.JLabel();
        campoEdad = new javax.swing.JTextField();
        tituloNombre3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(825, 448));

        bc.setBackground(new java.awt.Color(255, 255, 255));
        bc.setPreferredSize(new java.awt.Dimension(825, 448));

        titulo.setText("Registrar nuevo usuario");

        tituloNombre.setText("DNI");

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        tituloNombre1.setText("Nombre");

        tituloNombre2.setText("Apellido");

        tituloNombre3.setText("Edad");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setBackground(new java.awt.Color(18, 90, 173));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar Usuario");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bcLayout = new javax.swing.GroupLayout(bc);
        bc.setLayout(bcLayout);
        bcLayout.setHorizontalGroup(
            bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bcLayout.createSequentialGroup()
                .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bcLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bcLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bcLayout.createSequentialGroup()
                                .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNombre)
                                    .addGroup(bcLayout.createSequentialGroup()
                                        .addComponent(tituloNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                        .addGap(251, 251, 251))
                                    .addComponent(campoDni))
                                .addGap(30, 30, 30))
                            .addGroup(bcLayout.createSequentialGroup()
                                .addComponent(tituloNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addGap(308, 308, 308)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bcLayout.createSequentialGroup()
                                .addComponent(tituloNombre3, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addGap(298, 298, 298))
                            .addGroup(bcLayout.createSequentialGroup()
                                .addComponent(tituloNombre2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bcLayout.createSequentialGroup()
                                .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoEdad)
                                    .addComponent(campoApellido)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)))))
                .addContainerGap())
        );
        bcLayout.setVerticalGroup(
            bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bcLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bcLayout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bcLayout.createSequentialGroup()
                                .addComponent(tituloNombre1)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bcLayout.createSequentialGroup()
                                .addComponent(tituloNombre2)
                                .addGap(18, 18, 18)))
                        .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloNombre3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tituloNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addComponent(jSeparator1))
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bc, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = campoNombre.getText();
        String  apellido = campoApellido.getText();
        String aux = campoEdad.getText();
        String dni = campoDni.getText();
        
        
        int edad;
        
         
         
        

        if(nombre.isEmpty()||apellido.isEmpty()||aux.isEmpty()||dni.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar los campos \n","AVISO",javax.swing.JOptionPane.ERROR_MESSAGE);
            campoNombre.requestFocus();
            return;
        }
        
        if(aux.matches("^[0-9]+$")){
            edad = Integer.parseInt(aux);
        }else{
           javax.swing.JOptionPane.showMessageDialog(this, "Debe ser solo números \n","AVISO",javax.swing.JOptionPane.ERROR_MESSAGE);
           campoEdad.requestFocus();
           return; 
        }
        
        if(dni.length()!=9){
           javax.swing.JOptionPane.showMessageDialog(this, "Debe ser un DNI \n","AVISO",javax.swing.JOptionPane.ERROR_MESSAGE);
           campoDni.requestFocus();
           return;
        }
        
        UsersDB user1 =  (isEdition) ? user : new UsersDB();
        user1.setNombre(nombre);
        user1.setApellido(apellido);
        user1.setEdad(edad);
        user1.setDni(dni);
        
        try {
            DAOUsuarioImpl dao = new DAOUsuarioImpl();
            
            
            if(!isEdition){
                dao.registrar(user1);
            }else{
                  dao.modificar(user1);
            }
            
            String mensajePasodo = (isEdition) ? "modifcado" : "registrado";
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario " + mensajePasodo + " exitosamente \n","AVISO",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            if(!isEdition){
                campoNombre.setText("");
                campoApellido.setText("");
                campoEdad.setText("");
                campoDni.setText("");
            }
        } catch (Exception e) {
            String errorMensaje = (isEdition) ? "modifcado" : "registrado";
            System.out.println(e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "NO se " + errorMensaje+" usuario \n","AVISO",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bc;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoDni;
    private javax.swing.JTextField campoEdad;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloNombre;
    private javax.swing.JLabel tituloNombre1;
    private javax.swing.JLabel tituloNombre2;
    private javax.swing.JLabel tituloNombre3;
    // End of variables declaration//GEN-END:variables
}
