/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package biblioteca.biblioteca2.views;

import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class subirLibro extends javax.swing.JPanel {

    /**
     * Creates new form subirLibro
     */
    public subirLibro() {
        initComponents();
        InitStyles();       
    }
    
    private void InitStyles(){
        titulo.putClientProperty( "FlatLaf.style", "font: bold $h3.regular.font" );
        titulo.setForeground(Color.black);  
        tituloLibro.putClientProperty( "FlatLaf.style", "font: bold $h4.regular.font" );
        tituloLibro.setForeground(Color.gray);  
        tituloAutor.putClientProperty( "FlatLaf.style", "font: bold $h4.regular.font" );
        tituloAutor.setForeground(Color.gray);  
        tituloGenero.putClientProperty( "FlatLaf.style", "font: bold $h4.regular.font" );
        tituloGenero.setForeground(Color.gray);  
        tituloEditorial.putClientProperty( "FlatLaf.style", "font: bold $h4.regular.font" );
        tituloEditorial.setForeground(Color.gray);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bc = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        tituloLibro = new javax.swing.JLabel();
        campoTitulo = new javax.swing.JTextField();
        campoAutor = new javax.swing.JTextField();
        tituloAutor = new javax.swing.JLabel();
        campoGenero = new javax.swing.JTextField();
        tituloGenero = new javax.swing.JLabel();
        campoEditorial = new javax.swing.JTextField();
        tituloEditorial = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(856, 453));

        bc.setBackground(new java.awt.Color(255, 255, 255));
        bc.setPreferredSize(new java.awt.Dimension(856, 453));

        titulo.setText("Subir nuevo Libro");

        tituloLibro.setText("Título");

        campoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTituloActionPerformed(evt);
            }
        });

        campoAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAutorActionPerformed(evt);
            }
        });

        tituloAutor.setText("Autor/es");

        campoGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoGeneroActionPerformed(evt);
            }
        });

        tituloGenero.setText("Género/s");

        campoEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEditorialActionPerformed(evt);
            }
        });

        tituloEditorial.setText("Editorial");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout bcLayout = new javax.swing.GroupLayout(bc);
        bc.setLayout(bcLayout);
        bcLayout.setHorizontalGroup(
            bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bcLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bcLayout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bcLayout.createSequentialGroup()
                        .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bcLayout.createSequentialGroup()
                                .addComponent(tituloAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                .addGap(253, 253, 253))
                            .addComponent(campoAutor)
                            .addGroup(bcLayout.createSequentialGroup()
                                .addComponent(tituloLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(275, 275, 275))
                            .addComponent(campoTitulo))
                        .addGap(33, 33, 33)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoGenero, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bcLayout.createSequentialGroup()
                                .addComponent(tituloGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addGap(250, 250, 250))
                            .addComponent(campoEditorial)
                            .addGroup(bcLayout.createSequentialGroup()
                                .addComponent(tituloEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(257, 257, 257)))
                        .addGap(47, 47, 47))))
        );
        bcLayout.setVerticalGroup(
            bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bcLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titulo)
                .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bcLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tituloEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoTitulo)
                            .addComponent(campoEditorial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bcLayout.createSequentialGroup()
                                .addComponent(tituloGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
                            .addGroup(bcLayout.createSequentialGroup()
                                .addComponent(tituloAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoAutor)))
                        .addGap(94, 94, 94))
                    .addGroup(bcLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator1)
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bc, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bc, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTituloActionPerformed

    private void campoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAutorActionPerformed

    private void campoGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoGeneroActionPerformed

    private void campoEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEditorialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bc;
    private javax.swing.JTextField campoAutor;
    private javax.swing.JTextField campoEditorial;
    private javax.swing.JTextField campoGenero;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloAutor;
    private javax.swing.JLabel tituloEditorial;
    private javax.swing.JLabel tituloGenero;
    private javax.swing.JLabel tituloLibro;
    // End of variables declaration//GEN-END:variables
}
