/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package biblioteca.biblioteca2.views;

import biblioteca.biblioteca2.DAOUsuarioImpl;
import biblioteca.biblioteca2.biblioteca;
import biblioteca.biblioteca2.biblioteca2;
import biblioteca.interfacez.DAOUser;
import biblioteca.models.UsersDB;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Usuario extends javax.swing.JPanel {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
        InitStyles();
        LoadUsers();                
    }
    
    private void LoadUsers(){
        try {
           DAOUsuarioImpl dao = new DAOUsuarioImpl();
           DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
           dao.listar("").forEach((u) -> model.addRow(new Object[]{u.getId(),u.getNombre(),u.getApellido(),u.getEdad(),u.getDni()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());            
        }
    }
    
    private void InitStyles(){
        titulo.putClientProperty( "FlatLaf.style", "font: bold $h3.regular.font" );
        titulo.setForeground(Color.black);
        campoBuscador.putClientProperty("JTextField.placeholderText", "Ingrese el nombre de usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bc = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        campoBuscador = new javax.swing.JTextField();
        buscarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editarUsuario = new javax.swing.JButton();
        borrarUsuario = new javax.swing.JButton();
        nuevoUsuario = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(770, 434));

        bc.setBackground(new java.awt.Color(255, 255, 255));
        bc.setPreferredSize(new java.awt.Dimension(770, 434));

        titulo.setText("Usuarios");

        campoBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscadorActionPerformed(evt);
            }
        });

        buscarUsuario.setBackground(new java.awt.Color(18, 90, 173));
        buscarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        buscarUsuario.setText("Buscar");
        buscarUsuario.setBorderPainted(false);
        buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuarioActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Edad", "DNI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        editarUsuario.setBackground(new java.awt.Color(18, 90, 173));
        editarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        editarUsuario.setText("Editar");
        editarUsuario.setBorderPainted(false);
        editarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsuarioActionPerformed(evt);
            }
        });

        borrarUsuario.setBackground(new java.awt.Color(18, 90, 173));
        borrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        borrarUsuario.setText("Borrar");
        borrarUsuario.setBorderPainted(false);
        borrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarUsuarioActionPerformed(evt);
            }
        });

        nuevoUsuario.setBackground(new java.awt.Color(18, 90, 173));
        nuevoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nuevoUsuario.setText("Nuevo");
        nuevoUsuario.setBorderPainted(false);
        nuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bcLayout = new javax.swing.GroupLayout(bc);
        bc.setLayout(bcLayout);
        bcLayout.setHorizontalGroup(
            bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bcLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bcLayout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bcLayout.createSequentialGroup()
                        .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bcLayout.createSequentialGroup()
                                .addGap(445, 445, 445)
                                .addComponent(nuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(editarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(borrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bcLayout.createSequentialGroup()
                                .addComponent(campoBuscador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarUsuario)))
                        .addGap(33, 33, 33))))
        );
        bcLayout.setVerticalGroup(
            bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bcLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBuscador, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(buscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bc, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bc, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscadorActionPerformed

    private void buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuarioActionPerformed
        try {
           String usuario = campoBuscador.getText();                               
           DAOUsuarioImpl dao = new DAOUsuarioImpl();
           DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
           model.setRowCount(0);
           dao.listar(usuario).forEach((u) -> model.addRow(new Object[]{u.getId(),u.getNombre(),u.getApellido(),u.getEdad(),u.getDni()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());            
        }
    }//GEN-LAST:event_buscarUsuarioActionPerformed

    private void editarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarUsuarioActionPerformed
        //DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow() > -1){
            try{
            int id = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            DAOUser dao = new DAOUsuarioImpl();
            biblioteca2.ShowJPanel(new SubirUsuarios(dao.getUserById(id)));
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el usuario a editar.\n","AVISO",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        System.out.println(jTable1.getSelectedRow());
    }//GEN-LAST:event_editarUsuarioActionPerformed

    private void borrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarUsuarioActionPerformed
        DAOUsuarioImpl dao = new DAOUsuarioImpl();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        List<Integer> filasSeleccionadas = new ArrayList<>(); // Lista para guardar las filas seleccionadas
        
        
        if(jTable1.getSelectedRows().length < 1){
            
            javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar uno o más usuarios a eliminar.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            
        }else{
            
            for (int i : jTable1.getSelectedRows()) {
                filasSeleccionadas.add(i); // Guardar el índice de las filas seleccionadas
            }
            for (int i = filasSeleccionadas.size() - 1; i >= 0; i--) {
            int fila = filasSeleccionadas.get(i);            
                try {
           
                
                dao.eliminar((int)jTable1.getValueAt(fila, 0));
                model.removeRow(fila);
                } catch (Exception e) {
                    System.out.println(e.getMessage());            
                }
             
            }
        }
    }//GEN-LAST:event_borrarUsuarioActionPerformed

    private void nuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoUsuarioActionPerformed
        biblioteca2.ShowJPanel(new SubirUsuarios());
    }//GEN-LAST:event_nuevoUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bc;
    private javax.swing.JButton borrarUsuario;
    private javax.swing.JButton buscarUsuario;
    private javax.swing.JTextField campoBuscador;
    private javax.swing.JButton editarUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton nuevoUsuario;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
